#!/bin/bash
set -e
GXX="${GXX:-g++}"
cmake -G Ninja \
      -DCMAKE_C_COMPILER="$(${GXX} -print-prog-name=gcc)" \
      -DCMAKE_CXX_COMPILER="${GXX}" \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_CXX_STANDARD=17 \
      -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra" \
      -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi" \
      -DLLVM_BUILD_LLVM_DYLIB=ON \
      -DLLVM_LINK_LLVM_DYLIB=ON \
      -DLLVM_TARGETS_TO_BUILD=X86 \
      -DLLVM_ENABLE_BINDINGS=OFF \
      -DLLVM_INSTALL_TOOLCHAIN_ONLY=ON \
      -DLLVM_INCLUDE_BENCHMARKS=OFF \
      -DLLVM_INCLUDE_DOCS=OFF \
      -DLLVM_INCLUDE_TESTS=OFF \
      -DENABLE_EXPERIMENTAL_NEW_PASS_MANAGER=ON \
      -DCLANG_LINK_CLANG_DYLIB=ON \
      -DCLANG_DEFAULT_CXX_STDLIB=libc++ \
      -DCLANG_DEFAULT_OBJCOPY=llvm-objcopy \
      -DCLANG_ENABLE_ARCMT=OFF \
      -DLIBCXX_ABI_UNSTABLE=ON \
      -DLIBCXX_ENABLE_STATIC=OFF \
      -DLIBCXX_ENABLE_FILESYSTEM=ON \
      -DLIBCXX_ENABLE_STATIC_ABI_LIBRARY=ON \
      -DLIBCXXABI_ENABLE_SHARED=OFF \
      -DLIBCXXABI_INSTALL_LIBRARY=OFF \
      "$@"
